### ISSUE TITLE
Set up the kanban board[1pts]

### ISSUE THREAD

**Issue by vvoo21** [vvoo21/recipe-app#18]
Our kanban board : https://github.com/users/vvoo21/projects/1/views/1
Our group has three members:

@Feliverse 
@vvoo21 
@Metaverse-Nabeel

**Comment by Ismailco** [comment]
### Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️ Kanban board setup properly
✔️ All students have assigned tasks
✔️ Tasks divided properly

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
